import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./providers";
import { Inter } from "next/font/google";
import { cn } from "./shared-components/lib/utils";
import { Toaster } from "@/components/ui/toast";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("antialiased", "font-sans", inter.variable)}>
      <ClerkProvider>
        <body className="min-h-screen flex flex-col justify-center items-center">
          <Providers>{children}</Providers>
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
